### ISSUE TITLE
Add B0mapping functionality

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#11]
Add API function to compute phase maps to B0maps. Matlab repo dual echo [implementation](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/%2Bimutils/%2Bb0/dual_echo.m) (Look at PRs for potential updates to the file). #36 will need to be implemented first.

A CLI should also be added.

Flag suggestions
```
-phase input (filename)
-o output (filename)
```

Motivated by #37

**Comment by mathieuboudreau** [comment]
Do you mean B0 map fitting or B0 mapping data signal generation? If the latter, I've done it already in #5

**Comment by po09i** [comment]
I mean converting phase images to B0 maps. I'll update the name and description.

**Comment by po09i** [comment]
This can be closed as we now have prepare_fieldmap: #169
