### ISSUE TITLE
Add '_phasediff' to the concerned nifti file names (BIDS convention)

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#113]
### Description of Problem / Inefficiency:
During the dicom to nifti conversion process, the nifti containing phase difference images should be named as follows: 

```sub-<label>/[ses-<label>/]
    fmap/
        sub-<label>[_ses-<label>][_acq-<label>][_run-<index>]_phasediff.nii[.gz]
        sub-<label>[_ses-<label>][_acq-<label>][_run-<index>]_phasediff.json
```
According to the [BIDS convention](https://bep001.readthedocs.io/en/dev/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-1-phase-difference-image-and-at-least-one-magnitude-image).

### Implementation Suggestion:

Modifying the `config.json` file that is read out by dcm2bids during the conversion so that the correct names are given to the output files.

**Comment by po09i** [comment]
Issue can be closed, this was implemented in PR #191.
