### ISSUE TITLE
Update files in /docs/source with the new repository name

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#114]
### Description of Problem:

We have changed the repository name from `shimming-toolbox-py` to `shimming-toolbox`.
The documentation generated by 'ReadTheDocs' still links to the old repository name (shimming-toolbox-py).

### Suggestion:

We just need to update the links in `/docs` with the new repository name.

**Comment by jidicula** [comment]
I'll push a fix for this tonight
