### ISSUE TITLE
Make sure the environment is properly setup and binaries are present before running pytest

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#118]
A few steps are required for pytest to run, such as:
- [x] download testing data
- [ ] download 3rd party binaries (eg prelude, dcm2niix)

To prevent confusion (eg https://github.com/shimming-toolbox/shimming-toolbox/issues/102), we should have pytest validate the presence of the necessary files before running. Or, we could also have pytest download those files, as being done in [SCT](https://github.com/neuropoly/spinalcordtoolbox/blob/master/conftest.py)

**Comment by jidicula** [comment]
Resolution from internal discussion:

* set up conftest like in SCT (mentioned in issue description) that pulls test data into testing environment
* tests for soft dependencies (prelude and dcm2niix) to be opt-in, with a flag for each external dependency (e.g. `pytest --prelude`, `pytest --dcm2niix`) as well as an `--all` flag to run tests for all external dependencies
  * for opt-in dependency tests, check if the dependency is installed with litmus commands (version or help flags, then check command return code)
* end users can run `pytest` with no flags to test the "minimal" configuration that has no external dependencies
* each contributor is responsible for running `pytest` with the `--all` flag to ensure full coverage and good integration of their feature
* Travis checks will test all external dependencies as our safety net in case contributors forget to test comprehensively for all external dependencies

@jcohenadad did I catch everything?
