### ISSUE TITLE
__dir_testing__ should include the __dir_shimming_toolbox__ path

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#121]
### Description of Problem / Inefficiency:
`__dir_testing__` simply is `testing_data` and needs to be used in conjunction with `__dir_shimmingtoolbox__` to get an absolute path to avoid errors when being used. 

### Implementation Suggestion:
It should have the same behaviour as `__dir_config_dcm2bids__` which returns an abolute path.

Implementation suggestion:
`__dir_testing__ = os.path.join(__dir_shimmingtoolbox__, 'testing_data')`

**Comment by jcohenadad** [comment]
is it `__dir_shimmingtoolbox__ ` or `__dir_shimming_toolbox__ `? (the issue describes both)

in any case, the solution looks good to me

**Comment by po09i** [comment]
It's` __dir_shimmingtoolbox__`, I updated the description.
