### ISSUE TITLE
FSL and prelude not included in installation documentation

### ISSUE THREAD

**Issue by jidicula** [shimming-toolbox/shimming-toolbox#122]
### Checklist

- [x] I've given this issue a self-descriptive, meaningful title (e.g. *Installation failure: problem creating launchers*)
- [ ] I've described my environment
- [x] I've described the bug
- [ ] I've described the steps to reproduce the behaviour
- [ ] I've included screenshots
- [ ] I've given this issue the correct labels

### Environment details

- [x] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

Project version: N/A

Operating System and version: N/A

Python version: 3.x.x  N/A

Path to Python binary: /path/to/bin/python  N/A

### Bug Description

FSL and Prelude are a necessary dependency for the project but are not included in the documentation steps for installing and setting up shimming-toolbox.

### Reproduction Steps

N/A

### Potential Reasons behind Bug:

N/A
### Screenshots:

N/A
### Additional Context:

N/A

**Comment by gaspardcereza** [comment]
Note that you'll need python2 to execute the [FSL installer](https://fsl.fmrib.ox.ac.uk/fsldownloads_registration). 
I only tested the installation on Ubuntu 20 though.
