### ISSUE TITLE
FSL needs to be added to PATH

### ISSUE THREAD

**Issue by jidicula** [shimming-toolbox/shimming-toolbox#128]
The [FSL installation steps](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation) do not include the critical step of adding the FSL binary directory to your shell PATH. Therefore, this should be added to our documentation. Once this is added, I can tackle #118 .

**Comment by jcohenadad** [comment]
is it really our responsibility? it seems to be part of the 3rd party software installation (ie: we can assume that ppl install the software properly, by following FSL's instructions)

**Comment by jidicula** [comment]
FSL's instructions stop short of adding the suite to the PATH, so its own documentation steps for [checking that it was correctly installed](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/MacOsX#Checking_the_installation) don't work. 

I added the following line to my .zshrc (which can also be added to a user's .bash_profile, .bashrc, etc):

```bash
export PATH="/usr/local/fsl/bin:$PATH"
```
and only then does running their suggested litmus commands return the expected output:

```
$ flirt -version
FLIRT version 6.0
$ which imcp
/usr/local/fsl/bin/imcp
```

Without this clarification, none of the FSL binaries are available to the user unless they provide the full filepath (e.g. `$ /usr/local/fsl/bin/flirt`) for each binary, which is contrary to FSL's documentation.

**Comment by jidicula** [comment]
update: I dug into the `fslinstaller.py` and found where it tries to guess the user's shell profile location:

```python
def get_profile(shell):
    home = os.path.expanduser("~")

    dotprofile = os.path.join(home, '.profile')
    if shell == 'bash':
        profile = os.path.join(home, '.bash_profile')
        if not os.path.isfile(profile) and os.path.isfile(dotprofile):
            profile = dotprofile
    elif shell == 'zsh':
        profile = os.path.join(home, '.zprofile')
        # ZSH will never source .profile
    elif shell == 'sh':
        profile = dotprofile
    else:
        cshprofile = os.path.join(home, '.cshrc')
        if shell == 'csh':
            profile = cshprofile
        elif shell == 'tcsh':
            profile = os.path.join(home, '.tcshrc')
            if not os.path.isfile(profile) and os.path.isfile(cshprofile):
                profile = cshprofile
        else:
            raise ValueError("Unsupported shell")
    return profile
```

It won't set up properly if the user's ZSH is configured with a .zshrc file, like mine is, and instead adds it to .zprofile... I checked my system and found that it was added to this file in my home directory 🤦‍♂️ .

I don't recall what the default ZSH config file is on macOS, but if it's .zshrc and not .zprofile, should we include the instruction to add `source ~/.zprofile` to their `.zshrc`?

**Comment by jcohenadad** [comment]
> I don't recall what the default ZSH config file is on macOS, but if it's .zshrc and not .zprofile, should we include the instruction to add source ~/.zprofile to their .zshrc?

again, to me this is FSL's responsibility. We should not start supporting their software installation procedure. If there is a pb with zsh config file, i would post it on their repos (in fact, they use a mailing list)

**Comment by jidicula** [comment]
Sure thing, I'll close the issue.
