### ISSUE TITLE
Update utils section

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#151]
### Description of Problem / Inefficiency:
There is currently a utils.py file that stores miscellaneous functions. Before the file gets out of hand with a lot of functions, a refactoring could done to structure the utils section.

### Implementation Suggestion:
Create a utils folder with files that have topics:
- Unit conversion
- Download
- etc

**Comment by jcohenadad** [comment]
It is difficult to anticipate what and how many of those functions there will be, so for now, i suggest we keep status quo and reassess once the project is bigger, where/how we want to reorganize those APIs

**Comment by po09i** [comment]
Reassessing, the utils.py file is still manageable.
