### ISSUE TITLE
Click does not output while inside CliRunner.invoke

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#155]
### Bug Description
CliRunner allows to put breakpoints within a CLI script. However, printing variables while inside the invoke command do not show on the stdout. This makes it difficult to debug.

### Possible useful links
https://github.com/pallets/click/issues/939

**Comment by po09i** [comment]
click.echo() can be used to output on the python console

**Comment by jcohenadad** [comment]
click.echo() did not work for me.

The solution was to upgrade from Pycharm 2019 to 2020.

BTW: with 2020, both `print()` and `click.echo()` work 🎉
