### ISSUE TITLE
Check installation and versions of 3rd party binaries

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#161]
### Context

ST relies depends on the following non-Python packages:
- `dcm2niix`
- `prelude`

Given that the results of ST depend on the existence and version of these packages, we should probably implement a mechanism that checks if these software are installed (eg: `which XX` command) and their version.

Should we implement a `st_check_dependencies` as done in [SCT](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_check_dependencies.py)?

**Comment by jidicula** [comment]
I can grab this ticket, I think it's a good idea to verify the dependency installation setup is correct.

**Comment by jidicula** [comment]
Wait, actually this is *kind* of implemented already in the testing suite: https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html#testing-subsets-of-soft-dependencies (last case) . I feel like these checks are already part of the testing suite, so I'm not sure that a separate script is "needed", unless we want a script for only checking the dependency installation and availability, not to test the features that rely on said dependencies. In that case, it's a simple implementation to factor out `test_prelude_installation()` and `test_dcm2niix_installation()` from `conftest.py` into the new script, and also call that script from inside `conftest.py`.

What should the resolution be @jcohenadad ?

**Comment by po09i** [comment]
>  unless we want a script for only checking the dependency installation and availability

Having a script that the user could use to make sure everything is set up correctly could be very useful instead of running pytest and having lots of errors and having to look through them to see what is missing. Ideally the user would read the installation procedure and install the dependencies correctly but the script would allow to make sure everything is good in a visually pleasing way.

`sct_check_dependencies` also gives a lot of information about the system that could be useful in the future for bug reproducibility (we could ask the user to run st_check_dependencies and provide the log instead of manually writing all the environment information).

**Comment by jcohenadad** [comment]
FWIT, here is the output of `sct_check_dependencies`:

~~~
julien-macbook:~ $ sct_check_dependencies 

--
Spinal Cord Toolbox (5.0.0)

SCT info:
- version: 5.0.0
- path: /Users/julien/sct-test
OS: osx (Darwin-19.6.0-x86_64-i386-64bit)
CPU cores: Available: 16, Used by ITK functions: 16
RAM: Total: 16384MB, Used: 8844MB, Available: 6194MB
Check Python executable.............................[OK]
  Using bundled python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 17:50:39) 
[GCC Clang 10.0.0 ] at /Users/julien/sct-test/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if colored is installed.......................[OK] (1.4.2)
Check if dipy is installed..........................[OK] (1.3.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if ivadomed (2.4.0) is installed..............[OK] (2.4.0)
Check if Keras (2.1.5) is installed.................[OK] (2.1.5)
Check if matplotlib is installed....................[OK] (3.3.2)
Check if nibabel is installed.......................[OK] (3.2.0)
Check if numpy is installed.........................[OK] (1.19.4)
Check if pandas is installed........................[OK] (1.1.4)
Check if psutil is installed........................[OK] (5.7.3)
Check if pyqt5 (5.11.3) is installed................[OK] (5.11.3)
Check if pytest is installed........................[OK] (6.1.2)
Check if pytest-cov is installed....................[OK] (__version__ = '2.10.1')
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.24.0)
Check if requirements-parser is installed...........[OK] (0.2.0)
Check if scipy is installed.........................[OK] (1.5.4)
Check if scikit-image is installed..................[OK] (0.17.2)
Check if scikit-learn is installed..................[OK] (0.23.2)
Check if tensorflow (1.5.0) is installed............[OK] (1.5.0)
Check if torch (1.5.0) is installed.................[OK] (1.5.0)
Check if torchvision (0.6.0) is installed...........[OK] (0.6.0)
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.51.0)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3 is installed.......................[OK] (1.25.11)
Check if pytest_console_scripts is installed........[OK]
Check if pytest-xdist is installed..................[OK] (2.1.0)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if DISPLAY variable is set....................[OK]
Check if figure can be opened with PyQt.............[OK]
~~~
