### ISSUE TITLE
Add support for macOS on Travis CI

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#180]
### Feature Description:

To render our tests more sensitive to other platform (see e.g. https://github.com/shimming-toolbox/shimming-toolbox/pull/179), we should extend our CI to other platforms. 

The low hanging fruit is to add support to macOs since it is available in Travis.

**Comment by jidicula** [comment]
Are you planning to support macOS Big Sur on Apple Silicon (new MacBooks)? If so, note that Travis [doesn't support it](https://docs.travis-ci.com/user/reference/osx/#macos-version) (yet) and is also going to [start charging for macOS builds](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), but [GH Actions](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources) does have it as an option, and gives unlimited build minutes for public repos (like ours!).

I've been playing around with GH Actions [on my own dotfiles repo](https://github.com/jidicula/dotfiles/blob/master/.github/workflows/setup.yml) and it also allows lots of flexibility for matrix builds and conditional runs, so it seems pretty solid in terms of feature parity with Travis. Matrix builds could also allow for us to easily run CI/CD check&test suites against multiple Python versions in the future.

**Comment by jcohenadad** [comment]
Thank you for looking into it @jidicula 🙏 
For cross-referencing, we've been seriously considering GH actions for our other projects, see notably https://github.com/neuropoly/spinalcordtoolbox/issues/3057.

Would you be OK porting our current CI to GH actions? I can give you the required permissinos if needed

**Comment by jidicula** [comment]
> Would you be OK porting our current CI to GH actions? I can give you the required permissinos if needed

Sure thing! I don't think I'll need any extra permissions but I'll ping if I hit any walls. The approach I'm thinking is to follow @kousu's approach to factor CI steps into a shell script for portability, then call the shell script from the YAML for whatever platform strikes our fancy (https://github.com/neuropoly/spinalcordtoolbox/issues/3057#issuecomment-733872092).
