### ISSUE TITLE
Coveralls sometimes fails if the code coverage stays the same

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#196]
### Bug Description
Coveralls check sometimes fails if the code coverage stays the same.

### Reproduction Steps
Look at #195

**Comment by po09i** [comment]
This issue is relevant https://github.com/lemurheavy/coveralls-public/issues/565

It seems to be something to be fixed in coveralls. In the meantime, we can allow for very small decrease in code coverage (0.1%) to fix the problem.

**Comment by jidicula** [comment]
Was this fixed around the time you bump-committed 8e54122?

**Comment by po09i** [comment]
Yes. Thanks this can be closed. Fixed by changing the coveralls settings to allow up to 0.1% decrease. First implemented in 8e54122
