### ISSUE TITLE
Remove numbers in URLs from RTD

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#198]
### Context

Example of RTD link: https://shimming-toolbox.org/7_api_reference/api.html

### Problem

when adding this link in a paper/conference, this is ugly. 

### Solution

Change the link for https://shimming-toolbox.org/api-reference.html (or variations of it...)

**Comment by CodingApps** [comment]
@jcohenadad Could I handle this issue for you?

**Comment by CodingApps** [comment]
@jcohenadad I made the revisions to /docs/source/index.rst and renamed the directories to match the revised names. Numbers removed. Submitted the PR. Had difficulty with the 2GB FSL d/l to try it on my Mac. Has the dev environment worked well installed on a Mac? Was taking a while for the 2GB to complete.

**Comment by CodingApps** [comment]
@jcohenadad Fixed on PR https://github.com/shimming-toolbox/shimming-toolbox/pull/201 . Thx!

**Comment by jcohenadad** [comment]
thank you so much for your contribution @CodingApps !

**Comment by CodingApps** [comment]
@jcohenadad Absolutely! Keep upward! Will check back to pitch in down the road! Thx!
