### ISSUE TITLE
Add RF-shimming functionalities to the toolbox

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#208]
### Feature Description:
RF-shimming corresponds to the process of homogenizing the RF-field by optimizing the "shim-weights" (magnitude and phase) of every transmit elements. 

The main steps of the RF-shimming process are: 
1) Acquire a B<sub>1</sub> map for each transmit coil over the desired volume on the scanner,
2) Load the B<sub>1</sub> maps on the shimming-software (here `shimming-toolbox`),
3) Load SAR matrices that have been simulated on a software,
4) Run an optimization algorithm (e.g. reducing the [coefficient of variation](https://en.wikipedia.org/wiki/Coefficient_of_variation) while using the SAR  matrices as a constraint,
5) Send the obtained shim-weights to the scanner,

Many types of RF-shimming algorithms can be found in literature (e.g. slice-by-slice, dynamic, SAR efficient...). Here, we would first focus on a simple static volume-wise RF-shimming (one set of shim-weights is calculated to homogenize over the volume of interest). 

### Implementation Suggestion:

Here are suggestions of how we could organise our implementation to go through all these steps (**feedback is more than welcome !**) : 

- The B<sub>1</sub> maps are stored in a `DICOM` format. We would first have to convert them into `NIFTI` to be consistent with the B<sub>0</sub> mapping process. (This matter has already been discussed in #58 but we are still facing some issues due to the type of `DICOM` we have).

- Once stored into `NIFTI` files, the B<sub>1</sub> maps could be loaded using the [load_nifti](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/shimmingtoolbox/load_nifti.py) function (some adaptation might be needed)

- Regarding the SAR matrices: The Specific Absorption Rate corresponds to the energy received by the patient during the scan. For safety concerns, it must not exceed a specific threshold. SAR cannot be directly measured in the patient so it has to be estimated based on electro-magnetic simulations. 
The loading of the SAR matrices will mainly depend on the format we use to store them. In the Matlab code, they were just stored as `.mat` file containing a `nCoils x nCoils x nMeshes` matrix. This was obtained by using a MATLAB script on the CST (electromagnetic simulation software) raw output files to shape it into a `.mat` object. For our python code, I can think of several possibilities: 
    - Building a script that build a `numpy array` from the CST file (would not necessarily work for other softwares),
    - Considering that the user already has a SAR file for his coil and just load it (I don't know how most people store their SAR matrices but we would have to adapt to as many cases as we can imagine).

- Regrid the B<sub>1</sub> maps (based on the B<sub>0</sub> maps) in order to apply the same masking (we already have regridding functions that we could use/adapt).

- For the constrained optimization, we could chose to go with specific Python modules or try to adapt our own optimizer. 

- Sending the shim-weights to the scanner could be done manually (easy but time consuming and prone to human error) or automatically (might be hard to implement but worth it on a long term basis --> might not work with different scanners)

- It could be useful to display the expected  B<sub>1</sub> distribution  and the corresponding coefficient of variation once the optimization has been performed.

- I think it could be interesting to reuse/adapt some functions that we already have in the toolbox rather than developing slightly different ones (I think the code would thus remain clearer but I may be wrong).
 
- The `CLI `/`API` organisation of the code would be close to what we use for B<sub>0</sub> shimming in order to be logical for the user.

**This issue intends to be as clear as possible to everybody involved in the project so if blurry areas remain, please tell me and I will do my best to clarify things.**

**Comment by jcohenadad** [comment]
> The B1 maps are stored in a DICOM format. We would first have to convert them into NIFTI to be consistent with the B0 mapping process. (This matter has already been discussed in #58 but we are still facing some issues due to the type of DICOM we have).

don't bother with that from now-- start prototyping with NIfTI images (and upload in test data so you can start unit testing your prototype)

> Regarding the SAR matrices

This is a very complex discussion --> so i suggest we move the discussion to a specific issue (open issue and cross-ref here)

> Regrid the B1 maps (based on the B<sub>0</sub> maps) in order to apply the same masking

same as what?

> It could be useful to display the expected B1 distribution and the corresponding coefficient of variation once the optimization has been performed.

i suggest you elaborate on the visual outputs you have in mind-- again, this is very specific and isolated, so open an issue and cross ref

> The CLI /API organisation of the code would be close to what we use for B0 shimming in order to be logical for the user.

I suggest you start proposing some details of the algorithm, what CLI you envision, what existing API you can use. Again that could be the purpose of another specific issue

**Comment by charjl** [comment]
>Building a script that build a numpy array from the CST file (would not necessarily work for other softwares)

Why a numpy array? Could we make an object to store this similar to what we would get from matlab and put that in an array? The data therefore would fall under a "contract" (a super basic internal API) when creating the object, and so we could add plugins for other other software as needed. 

>For the constrained optimization, we could chose to go with specific Python modules or try to adapt our own optimizer.

What is needed/included in "constrained optimization"

> Sending the shim-weights to the scanner could be done manually (easy but time consuming and prone to human error) or automatically (might be hard to implement but worth it on a long term basis --> might not work with different scanners)

I like the automation idea, but I suggest we do manual first, and then add in the automatic solution afterwards. Scanners are tricky but I have done scripts that worked for the majority of scanners, and if that doesn't work, an internal API might just do it.

> It could be useful to display the expected B1 distribution and the corresponding coefficient of variation once the optimization has been performed.

Yes, please. For interest sake, and it makes integration testing easier.

>I think it could be interesting to reuse/adapt some functions that we already have in the toolbox rather than developing slightly different ones (I think the code would thus remain clearer but I may be wrong).

Yes. Needs DDD domain/service pattern. Don't worry, it's fun!!

>The CLI /API organisation of the code would be close to what we use for B0 shimming in order to be logical for the user.

Where can I see this?

**Comment by po09i** [comment]
Now that some B1 specific code will be introduced, we should think of the overall organization of the repo.

I suggest going with creating shimmingtoolbox/b0 and shimmingtoolbox/b1 and move the code specific to each one and keep the one that can be used by both out. (realtime_zshimming is B0 specific but dicom_to_nifti would be out of these 2 folders) It would look a bit like this:

- shimmingtoolbox/
  - cli
    - prepare_b0_fieldmap.py
    - prepare_b1_fieldmap.py
    - ...
  - masking/
  - simulate/
  - b0/
    - optimizer/
    - unwrap/
    - shim/
    - prepare_fieldmap.py (B0)
  - b1/
    - optimizer/ (eventually)
    - shim/
    - prepare_fieldmap.py (B1)
  - coils/
  - load_nifti.py
  - dicom_to_nifti.py
  - pmu.py
  - ...

> Where can I see this?

All CLIs are in shimmingtoolbox/cli

**Comment by jcohenadad** [comment]
@po09i i agree with your suggestion in https://github.com/shimming-toolbox/shimming-toolbox/issues/208#issuecomment-763047514. It is very difficult to predict the amount of overlap that will occur between b0 and b1, but we need to start somewhere, and this is a good suggestion to start, because there will inevitably be differences between b1 and b0 at some point.

**Comment by po09i** [comment]
Now that we have more code in PR #299

I think going the `shimmingtoolbox/b0` and `shimmingtoolbox/b1` route at this point seems overkill since the main difference is the shim folder. However this might not always be the case so I would refer to @gaspardcereza's expertise in B1 for his future work on shimming toolbox about what he thinks is missing or could benefit ST. If you think B1 will require code in other folders that would not easily be implemented in the other functions (`read_nii()` for example is fine for both B0 and B1), then we should go with a `/b0` and `/b1` folder at the top level.

If that's not the case and the `/shim` folder is the "only" folder that would benefit from a clear separation, then I would suggest to have `shimmingtoolbox/shim/b0`, `shimmingtoolbox/shim/b1` folders and `shimmingtoolbox/shim/shim_utils.py` and/or other relevant functions useful to both B0 and B1 in the folder `shimmingtoolbox/shim`.

What do you all think?

**Comment by gaspardcereza** [comment]
At this point I don't know what other manufacturers' B1 data would look like, but for Siemens and the way I implemented the RF shimming code so far, the second option seems good enough. The few functions inherent to B1 shimming are currently directly implemented in the `b1shim.py` file and I don't really expect to need many more since we want to use the same resampling and masking functions as for B0.

**Comment by po09i** [comment]
This was closed by mistake
