### ISSUE TITLE
Establish strategy for dealing with B0 coil profiles

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#21]
Specs for the coil profile data:
- Format: nii.gz
- Where to host: new repos on https://github.com/shimming-toolbox organization

Function to deal with these coil profiles:
- Open them (input: nifti)
- Put them in the same coordinate system as the destination data (e.g. fieldmap of specific subject) → use nibabel and scikit-image routines for interpolation and q/sform-based registration

To consider:
- Create tests for resampling coil profile to fieldmap (ie make sure coordinate system-based registration works as expected)
- What happens if coil profile is made in another scanner?

**Comment by rtopfer** [comment]
@po09i 3x coil profiles.mat in the [google drive](https://drive.google.com/drive/folders/1-8jwFoxn1A8RaS1gEo4qISKtoloD_ht8?usp=sharing) (likely a permissions issue if you couldn't access them before)

**Comment by jcohenadad** [comment]
i suggest we select the lightest coil profiles for the purpose of testing

**Comment by jcohenadad** [comment]
Related to https://github.com/shimming-toolbox/shimming-toolbox-py/issues/20#issuecomment-672128093

**Comment by po09i** [comment]
Proposed strategy: As proposed on https://github.com/shimming-toolbox/shimming-toolbox-py/issues/20#issuecomment-672128093, create synthetic coil profiles based on spherical harmonics. 

- Create a simple spherical harmonics that can output basis sets (x,y,z,order/degree)
  - `spherical_harmonics(orders, x, y, z)` (port from matlab the spherical_harmonics.m file up to the legendre calculation (already a python function `lpmv`))

scipy.special.sph_harm Testing with the function seems to require considerable modifications.

- Reorder and scale to siemens
  - Siemens_basis(x, y, z)

These functions would enable to be used as coil profiles for the optimizer and sequencer.
