### ISSUE TITLE
check_env.py does not catch the if an incorrect version of dcm2niix is installed

### ISSUE THREAD

**Issue by charjl** [shimming-toolbox/shimming-toolbox#211]
### Checklist

- [x] I've given this issue a self-descriptive, meaningful title (e.g. *Installation failure: problem creating launchers*)
- [x] I've described my environment
- [x] I've described the bug
- [x] I've described the steps to reproduce the behaviour
- [N/A] I've included screenshots
- [x] I've given this issue the correct labels

### Environment details

- [x] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

Project version:

Operating System and version:
Windows Subsystem for Linux 2 (Linux Kernel for Windows)

Python version: 3.x.x note that this software only supports 3.7 or greater

Path to Python binary: /path/to/bin/python 

![image](https://user-images.githubusercontent.com/2449020/105405926-195ac080-5c02-11eb-8a85-f24605409cdd.png)

### Bug Description
<!-- Describe the unexpected behaviour.
Where there is an incorrect (older) version of dcm2niix installed, the check_env.py should catch this as a missing requirement.
Instead, it completes without error.

### Reproduction Steps
1. Download an older version of dcm2niix
2. Run check_env.py
3. Observe the terminal output does not include information on the incorrect version of dcm2niix

### Potential Reasons behind Bug:
In check_env.py, we only check if dcm2niix is installed, but do not check the version(in and around line 75)

### Additional Context:
This is a "silent" failure which affects pytest.

**Comment by po09i** [comment]
We no longer look for dcm2niix since it is installed with the package.
