### ISSUE TITLE
The link to the `contribution guidelines` in the Readme is dead

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#212]
Operating System and version:
Tested in Windows 10 (Chrome) and MacOs Big Sur (Safari)

### Bug Description
When clicking on the contribution guidelines link on the [shimming-toolbox's GitHub page](https://github.com/shimming-toolbox/shimming-toolbox), I'm redirected to https://github.com/shimming-toolbox/shimming-toolbox/blob/master/docs/source/3_contributing/CONTRIBUTING.rst which doesn't exist anymore.

### Reproduction Steps
Click on the link in the readme section.

### Potential Reasons behind Bug:
We removed the section numbers in the documentation folder but not in the readme. 
The link should either redirect [here]( https://shimming-toolbox.org/en/latest/contributing/CONTRIBUTING.html#) (ReadTheDocs) or [here ](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/docs/source/contributing/CONTRIBUTING.rst) (GitHub). 

### Screenshots:
![image](https://user-images.githubusercontent.com/54723104/106015079-1ccfcb00-608c-11eb-9ef3-142a0a9da43d.png)

**Comment by gaspardcereza** [comment]
@jcohenadad @po09i @jidicula @charjl Is it better to update the link to redirect to ReadTheDocs or to the GitHub file? I'd personally go with RTD.

**Comment by jidicula** [comment]
@gaspardcereza agreedo, the RTD is prettified too, and encourages reading of other project documentation if the contributor is curious (which they should be doing anyway!)

**Comment by jidicula** [comment]
Also as part of this ticket, the link in this md file can also be updated: https://github.com/shimming-toolbox/shimming-toolbox/blob/master/.github/contributing.md

**Comment by gaspardcereza** [comment]
@jidicula Alright I'm on it !

**Comment by po09i** [comment]
This can be closed
