### ISSUE TITLE
Phantom ROI generation approach

### ISSUE THREAD

**Issue by evaalonsoortiz** [shimming-toolbox/shimming-toolbox#217]
Currently, when generating an ROI in a phantom scan an ROI can be generated in the centre of the FOV of an image with a predetermined size. 

In cases were the region of interest is not centred in the FOV (this is common in phantom setups) it might be preferable to have the ROI centred at a voxel location that the user specifies. That voxel location could be identified by the user independently by using fsleyes for example.

**Comment by po09i** [comment]
With our current features, it is possible to specify the voxel location of the middle of the ROI. For example, `st_mask box` has a `-center` option to specify that.

**Comment by evaalonsoortiz** [comment]
Great! I didn't catch that from the description, but re-reading it now it makes sense. I'll close this issue then.
