### ISSUE TITLE
Choice of units for RF maps

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#219]
## Context
I am currently implementing a function that takes a `NIFTI` file containing the RF data acquired at the scanner (#210). I would like to discuss with the team about the choice of units that we should use for the RF-maps.

This `NIFTI` file is obtained by calling `dcm2niix` on a folder containing the raw `DICOM` files from the scanner. (The data I have are from a Turboflash standard B1 mapping sequence on the MNI's Siemens Terra 7T scanner). 
Siemens stores the data as follows: 
- Magnitude values are stored in `degrees x 10` (I base myself on a previous Matlab code developed by Robarts but I don't know how to double check that: ideas are more than welcome !)
- Phase values are stored in the range `[248 - 3848]`

This is the case for the RF data acquired using Siemens's standard mapping sequence, but I don't think it is a universal way of storing values...

## Suggestions

- For the magnitude, we need a unit that takes into account the scaling with the voltage applied (e.g. T/V or degree/V). B0 maps are expressed in Hz but Hz/V but that might not be very adapted to the RF field. I would personally go with T/V in order to respect the SI units. 
  * Here are some units that can be found in literature (Feel free to ad units/articles): 
    *  Degree ([Jiru 2006](https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.21083), [Yarnykh 2007](https://pubmed.ncbi.nlm.nih.gov/17191242/), [Wang 2009](https://onlinelibrary.wiley.com/doi/abs/10.1002/nbm.1403), [Akoka 1993](https://www.sciencedirect.com/science/article/abs/pii/0730725X9390078R?via%3Dihub), [Wu 2019](https://onlinelibrary.wiley.com/doi/full/10.1002/nbm.3313), [Guérin 2014](https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.24800), [Grissom 2010](https://www.openaccessjournals.com/articles/improving-highfield-mri-using-parallel-excitation-11031.html))
    * T/uT/nT ([Padormo 2015](https://onlinelibrary.wiley.com/doi/full/10.1002/nbm.3313), [Setsompop 2008](https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.21739), [Guérin 2014](https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.24800))
    * Normalized/relative units ([Boudreau 2017](https://www.sciencedirect.com/science/article/pii/S1064185883711332), [Eggenschwiler 2011](https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.23145), [Setsompop 2008](https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.21739))
    * Gauss ([Insko 1993](https://www.sciencedirect.com/science/article/pii/S1064185883711332), [Sacolick 2010](https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.22357))

- For the phase, I think the best way is to go with a scaling between [-pi, pi] to be consistent with what we do for B0 phase (output of `read_nii`).

## Additional thoughts and problems
I noticed that all my phase images have a "zeroed line" on the left, as shown below (it is already there in the `DICOM` files so it is due to the scanner, not the code).  I think we could just set it as 2048 (no phase offset -> green on the image) before applying the scaling but maybe I'm missing a potential problem that this might induce. Has anyone seen that in the past ?
![image](https://user-images.githubusercontent.com/54723104/106649547-bf41ef80-655f-11eb-9728-1aee4f863959.png)

**Comment by po09i** [comment]
@gaspardcereza I want to correct a couple of statements. For B0, we currently don't scale the magnitude data, it is mostly not used actually, the only current use is within prelude to mask the phase map. They stay in their original siemens scaling. 
The phase is rescaled to hz.

I would make sure the phase range you mention is not due to noise or other factors. It looks like it could be from 0 to 4095.

**Comment by jcohenadad** [comment]
> but Hz/V but that might not be very adapted to the RF field

why is that?

> I would personally go with T/V in order to respect the SI units.

Hz and V are also part of [SI units](https://www.nist.gov/pml/weights-and-measures/si-units-time#:~:text=The%20SI%20unit%20for%20frequency,as%20one%20cycle%20per%20second.). 

> For the phase, I think the best way is to go with a scaling between [-pi, pi] to be consistent with what we do for B0 phase.

👍 
Just to be accurate on the notation, it would either be (-pi, pi] or [-pi, pi) (not [-pi, pi]).

about the artifact:

>  I think we could just set it as 2048 (no phase offset -> green on the image) before applying the scaling but maybe I'm missing a potential problem that this might induce. 

why deal with it in a particular way? we can just apply the scaling to all voxels, including these zeroed values. RF shimming will use masking anyway.

> Has anyone seen that in the past ?

Yes

**Comment by gaspardcereza** [comment]
> I would make sure the phase range you mention is not due to noise or other factors. It looks like it could be from 0 to 4095.

I check on the phase images and the wrap seems to happen at 3848 (it goes back to 248) as can be seen below in a zoomed wrapped region: 
![image](https://user-images.githubusercontent.com/54723104/106683447-85d6a780-6592-11eb-8901-0ffbc1cd2b4a.png)

Moreover this is consistent with what Kyle told me, even if I agree that it is not the most logical way to scale data.

> why is that?

I was thinking that expressing the RF field amplitude in Hz could be confusing for the users. But the choice of T over Hz is mainly a personal preference so it would be great to have other points of view. 

>why deal with it in a particular way? we can just apply the scaling to all voxels, including these zeroed values. RF shimming will use masking anyway.

If It remains in the image during scaling, as it is out of the [248, 3848) range, it will also results in values outside of the [-pi, pi) range. As you said, it is not a problem as we will be masking the data before shimming, but I just thought it might be weird for visualisation (e.g. for future GUI).

> Yes

Just out of curiosity, do you know why it might happen ? I tried to think about possible causes but except for a padding in order to make the matrix square, in don't see what could result in an empty line in the spatial domain...

**Comment by jcohenadad** [comment]
> Phase values are stored in the range [248 - 3848]

how do you get that?

> I was thinking that expressing the RF field amplitude in Hz could be confusing for the users.

Based on what arguments? refs? literature? etc.

> Just out of curiosity, do you know why it might happen ?

We asked Kyle this during one of our (recorded) session-- I forgot his answer but you could reach out to him or revisit the recording (and document in this thread)

**Comment by gaspardcereza** [comment]
> how do you get that?

I checked on my phase data (see my previous comment with the zoom on a wrap) and indeed, except for the null line on the left, all phase values range between 248 and 3848.

> Based on what arguments? refs? literature? etc. 

Mainly the fact that I didn't saw a lot of B1 maps in Hz (I saw a lot of normalized ones or often in nT/V). But I don't see any major problem with Hz (and as you mentioned it is part of the SI units). What I was referring to as confusing is the fact that we are talking about a RF field amplitude by using the Hz unit so it might be confusing with the real frequency of the field (but the order of magnitude will be very low compared to 297MHz so people shouldn't be too confused).

> We asked Kyle this during one of our (recorded) session-- I forgot his answer but you could reach out to him or revisit the recording (and document in this thread)

I'll give a look at the videos, and if I don't find anything I'll ask Kyle. I'll let you know ! 

Thanks for the feedback

**Comment by jcohenadad** [comment]
> I checked on my phase data (see my previous comment with the zoom on a wrap) and indeed, except for the null line on the left, all phase values range between 248 and 3848.

these numbers are based on one acquisition. How can you be sure you'll get the same number in another acquisition?

> Mainly the fact that I didn't saw a lot of B1 maps in Hz (I saw a lot of normalized ones or often in nT/V)

that was precisely what I was asking you to do: review the literature and document it in this thread. In the future, if we are asked to justify our decision, we can say it is based on X% of articles (out of Y articles considered, and listing all the articles), which use these units. It is a stronger argument than saying "i think people use mostly that".

**Comment by gaspardcereza** [comment]
> These numbers are based on one acquisition. How can you be sure you'll get the same number in another acquisition?

I checked on every standard turboflash RF mapping acquisitions that we did at the MNI (21/02/2020 - 23/09/2020) and they all have the same characteristics: a null line on the left edge and phase value ranging from [248 - 3848) everywhere else. But I guess it is specific to that sequence in particular (and maybe to the scanner itself ?). 

Also, I went through the XX that we did on 23/09/2020 to get an answer about the null values but couldn't find anything (I might have missed it in the ~4h of video though). Maybe this was during another session (from last February) but I couldn't find the recordings we did back then on the google drive... 
I should probably ask Kyle for a quick meeting in order to clarify all that and document it here and in the code. 

> That was precisely what I was asking you to do: review the literature and document it in this thread. In the future, if we are asked to justify our decision, we can say it is based on X% of articles (out of Y articles considered, and listing all the articles), which use these units. It is a stronger argument than saying "i think people use mostly that".

I will add that in the description of the issue. Done @jcohenadad

**Comment by jcohenadad** [comment]
> a null line on the left edge and phase value ranging from [248 - 3848) everywhere else. But I guess it is specific to that sequence in particular (and maybe to the scanner itself ?).

strange-- would be good to get Kyle's feedback on this

**Comment by po09i** [comment]
RF shimming is now implemented
