### ISSUE TITLE
Porting teensy communication with shimming boards.

### ISSUE THREAD

**Issue by alexfoias** [shimming-toolbox/shimming-toolbox#22]
The idea is to refactor the matlab serial communication into python. This will be done for the moment only for the shim amplifier boards and not for the pressure probe.

While working with python we could use [this](https://pyserial.readthedocs.io/en/latest/index.html) library.

**Comment by kousu** [comment]
I've used pyserial! It's pretty solid.

You actually don't need it though. You just need to `arduino = open("/dev/ttyS0", "r+b"))` -- I've used embedded systems like that before. pyserial's main feature is [list_ports()](https://pyserial.readthedocs.io/en/latest/tools.html#module-serial.tools.list_ports). Everything else is just a thin wrapper. I would say: try it with `open()` first and if that doesn't work then add pyserial.

(and a minor terminology note while I'm here: this is "porting" not "refactoring". Refactoring means rearranging existing code, especially finding common parts and replacing them with subroutines and objects, the way you can change a formula from an expanded polynomial to a product of two polynomials. Hope that helps!)

**Comment by gab-berest** [comment]
also pyserial is commonly used and makes it easy to get help if it doesn't work (which can happen a lot when dealing in communication between hardware devices)

**Comment by po09i** [comment]
@4rnaudB ported the teensy communication to Python
