### ISSUE TITLE
Add masks for RIRO and Static in realtime_zshimming

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#220]
### Description of Problem / Inefficiency:
With the goal of improving our realtime zshimming workflow, we can enhance our masking capability. We currently mask the shimming region we want to improve. Adding the ability to mask the riro component and the static component independently would be a nice feature and a lead to further investigations.

### Implementation Suggestion:
Add an option that inputs a mask for RIRO and use the current one for static (or vice versa)

**Comment by po09i** [comment]
PR #209 will change a lot of the current code for realtime zshimming, I expect the changes from this issue will be quick. @evaalonsoortiz are you okay to fix the merge problems that might come up from working in parallel since I expect the changes to be quite fast or do you want me to wait until your PR is merged so we don't run into merging conflicts?

**Comment by evaalonsoortiz** [comment]
Go ahead without me finalizing PR #209. I've run into problems when using that PR with multislice B0 maps anyhow, so there's more work to be done there.
