### ISSUE TITLE
Consider changing "_" for separating 2 words CLI options

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#222]
### Description
We should decide how to call CLI options that have more than one word. We have been separating the words with "_". We could also chose "-".

For now we have been using "-mask_static" and "-remove_tmp". We could consider using "-mask-static" and "-remove-tmp".

**Comment by po09i** [comment]
Related to https://github.com/shimming-toolbox/shimming-toolbox/pull/221#issuecomment-774256375

**Comment by po09i** [comment]
Pro:
- Faster to write
- Seems to be the default for naming options (according to click [documentation](https://click.palletsprojects.com/en/7.x/options/#name-your-options))

Cons:
- Blends in with the first "-" to specify a new option

**Comment by jcohenadad** [comment]
we could also take the opportunity to go with the standard "-" (short) and "--" (long) flags. I know we discussed it in the past and agreed for a single "-" for long, but that goes against the UNIX convention...

**Comment by charjl** [comment]
Similar to what Julien said. - for one letter implementation shortcuts, and always -- for anything longer than one letter is considered a terminal standard in most cases.
As joining words together goes, aka - vs _,  I prefer - as it is easier to see on many more terminals

**Comment by po09i** [comment]
Consensus after lab meeting: we go for double dash, and ignore single dash single char. Main argument: go with Linux standard.
