### ISSUE TITLE
Add dropdown button to select shim algorithm in GUI

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#233]
### Feature Description:
In the GUI, we want to be able to select the shim algorithm.
According to the chosen algorithm,  the input/output layout displayed in the GUI should change.

### Implementation Suggestion:
We think about embedding the different tabs corresponding to each algorithm in the `shim` tab. The choice of the algorithm would be don via a [ComboBox ](https://wxpython.org/Phoenix/docs/html/wx.ComboBox.html)or a [Choice](https://wxpython.org/Phoenix/docs/html/wx.Choice.html) input.

**Comment by po09i** [comment]
This was implemented [here](https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/pull/1). This can be closed.
