### ISSUE TITLE
Enhancement: Implementation of Additional "Nice to have" GUI features

### ISSUE THREAD

**Issue by charjl** [shimming-toolbox/shimming-toolbox#234]
### Checklist

- [ ] I've given this issue a self-descriptive, meaningful title (e.g. *Document the use of config/dcm2bids.json*)
- [ ] I've described the enhancement for an existing feature
- [ ] (optional) I've added some ideas about how to implement my suggestion
- [ ] I've given this issue the correct labels

### Implementation Suggestion:
Placeholder for:
- Having fsleyes that is opened from our product environment to auto load our plug in
- moving the st panel off of the images, but still above the other panels

**Comment by po09i** [comment]
fsleyes issues have moved to the "new" [repo](https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/issues). I opened these issues in that repo: https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/issues/60
