### ISSUE TITLE
Installation section is confusing

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#236]
### Checklist

- [ ] I've given this issue a self-descriptive, meaningful title (e.g. *Implement optimization algorithms for shimming*)
- [ ] I've described the new feature and its expected behaviour
- [ ] I've described the usage scenario for the new feature
- [ ] (optional) I've added some ideas about how to implement my suggestion
- [ ] I've given this issue the correct labels

### Feature Description:

When navigating on the installation page. It is unclear what belongs to conda installation and ST installation-- we should update the hierarchy. Example of inspiration 👉  https://axondeepseg.readthedocs.io/en/latest/documentation.html#installation

**Comment by po09i** [comment]
Comments from Daniel:
1. Should steps following the setup of the venv be run in the venv or not? It is not clear if you need the venv only to run the toolbox, or to install it as well. I ran them inside the venv, as that seems to be the intention.
2. I think all pre-requisites should be grouped together. A moron in a hurry could easily miss the prerequisite of FSL
3. What should the user do if the pytest fails?
4. Is FSL a hard dependency? At first it seems to be, but prelude (I assume this is the FSL module) is then referred to as a soft dependency

**Comment by po09i** [comment]
> 1. Should steps following the setup of the venv be run in the venv or not? It is not clear if you need the venv only to run the toolbox, or to install it as well. I ran them inside the venv, as that seems to be the intention.

This goes in favour of creating launchers

> 2. I think all pre-requisites should be grouped together. A moron in a hurry could easily miss the prerequisite of FSL

The section could use some revisiting. 

> 3. What should the user do if the pytest fails?

  Open an issue

> 4. Is FSL a hard dependency? At first it seems to be, but prelude (I assume this is the FSL module) is then referred to as a soft dependency

  The FSL suite is not required, only fsleyes for the gui and prelude for the unwrapper but the user does not need FSL at all to run most parts of the toolbox.

**Comment by gaspardcereza** [comment]
> The FSL suite is not required, only fsleyes for the gui and prelude for the unwrapper but the user does not need FSL at all to run most parts of the toolbox.

Is there a way to only install Prelude without the whole FSL package as it can be done for FSLeyes?

**Comment by jcohenadad** [comment]
> Is there a way to only install Prelude without the whole FSL package as it can be done for FSLeyes?

i don't think so

EDIT: not "in a clean way" (ie: we currently do it for the CI but this is a dirty hack because we already know what is the OS of the CI server)

**Comment by po09i** [comment]
We have revamped the installation section. https://github.com/shimming-toolbox/shimming-toolbox/pull/348
