### ISSUE TITLE
Consider creating launchers for CLIs

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#237]
### Context

Currently, to use ST, users have to set up their virtual environment. This is cumbersome, some users will forget to activate the environment, etc. 

Alternatively, in SCT, we have runners that activates the venv and then run the code inside the controlled environment. Installation of SCT is done via a shell script that takes care of creating a conda environment and creating the launchers:

https://github.com/neuropoly/spinalcordtoolbox/blob/900d29753117246fbb39d3ea07d642725a004b23/install_sct#L629

**Comment by jcohenadad** [comment]
a corollary benefits of that approach, is that we don't need to have FSLeyes installed (and run) within the same venv, which is known to cause installation issues https://github.com/neuropoly/spinalcordtoolbox/issues/3262

**Comment by po09i** [comment]
As mentioned in issue #240, we have found that fsleyes can now be more easily installed. We don't need fsleyes to be installed in the venv. We only need to run fsleyes from the venv. Launchers would still have the benefit to be able to launch fsleyes outside the venv. 

I believe this decreases the priority of the launchers as the installation process was the main argument behind going with launchers.

**Comment by jcohenadad** [comment]
> I believe this decreases the priority of the launchers as the installation process was the main argument behind going with lauchers.

indeed!
