### ISSUE TITLE
Bug when using FSLeyes Plugin dropdown on Mask tab

### ISSUE THREAD

**Issue by ahill187** [shimming-toolbox/shimming-toolbox#243]
### Environment details

- [x] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

Project version:

Operating System and version: MacOSX 10.16 (Big Sur)

Python version: 3.8.5

Path to Python binary: /Users/work/miniconda/envs/shim_venv/bin/python3

### Bug Description
The `st_plugin` has a bug when using the dropdown menu for the **Mask** tab. The blue information and red asterisk icons don't show up unless you switch tabs. They should show up immediately when you select an item from the dropdown.

### Reproduction Steps

1. Launch `fsleyes`, and make sure the `st_plugin` is loaded. 
2. Then click:

      **Settings** -> **Ortho View 1** -> **Shimming Toolbox**

3. The **Shimming Toolbox** plugin should now appear. There are 4 tabs. Click on the **Mask** tab.

![shimming-mask-1](https://user-images.githubusercontent.com/23019211/111010081-4e55da80-834a-11eb-86b0-c61683ca9df3.png)

4. From the dropdown menu, select **Rectangle**. You will notice, both the blue information icons and the red asterisks have disappeared.

![shimming-mask-2](https://user-images.githubusercontent.com/23019211/111010125-69c0e580-834a-11eb-9820-6ac7e727dc7b.png)

5. Now click on any other tab (**Shim**/**Field Map**/**Dicom to Nifti**).
6. Go back to the **Mask** tab. You should see that the blue information icons and the red asterisks have now appeared.

![shimming-mask-3](https://user-images.githubusercontent.com/23019211/111010133-6fb6c680-834a-11eb-9e6e-820d37533b1a.png)

### Potential Reasons behind Bug:
Something to do with `wxpython`, it has to do with the refreshing or `Layout()` calls I think.

**Comment by po09i** [comment]
This problem is also happening for any dropdown we have. (In the shim tab, the unwrapper section of the fieldmap tab)

**Comment by gaspardcereza** [comment]
Note: I don't have this problem on my end.

**Comment by po09i** [comment]
Fixed in the plugin repo
