### ISSUE TITLE
Add ability to average different echoes for better SNR for masking

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#245]
### Description of Problem / Inefficiency:
When running `st_mask sct` on a file with low SNR. SCT has a hard time with the segmentation, we are already averaging across time points if the input is 4d. However, we could further improve by averaging across echoes. The reason we are not currently doing so is that the BIDS convention separates the echoes in different files. This means that it is not trivial to average across echoes.

### Implementation Suggestion:
I see  ways of going with this:
- Create `st_image concat file1.nii.gz file2.nii.gz --axis 4` which would concatenate the files into one file
- Modify `st_mask sct` to search within the folder of the input file for other echoes
- Modify `st_mask sct --input` to allow for multiple input files (the different echoes)

I'm leaning towards the first option as it is more robust and allows to have the same benefit for multiple masking methods (BET, SCT, threshold)

**Comment by jcohenadad** [comment]
we are opening a pandora box for introducing image/maths manipulations. But i guess this is needed in the long term. A temporary alternative would be to leverage SCT fsleyes plugin to do these things (it also works for brain data). 

also, i guess what you want is more than concatenate: you want to average across files. Which could be done by:
- concatenating across 4th dim and then average across 4th dim, or
- inputting a list of files and averaging (ie: skip the concatenation step). 

i find the latter approach more intuitive (and also less clicks required).
