### ISSUE TITLE
Implement realtime shimming module in the optimizer

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#257]
### Checklist

- [ ] I've given this issue a self-descriptive, meaningful title (e.g. *Implement optimization algorithms for shimming*)
- [ ] I've described the new feature and its expected behaviour
- [ ] I've described the usage scenario for the new feature
- [ ] (optional) I've added some ideas about how to implement my suggestion
- [ ] I've given this issue the correct labels

### Feature Description:

TODO

**Comment by po09i** [comment]
https://github.com/shimming-toolbox/shimming-toolbox/pull/296
