### ISSUE TITLE
Implement BET for brain masking

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#258]
### Checklist

- [ ] I've given this issue a self-descriptive, meaningful title (e.g. *Document the use of config/dcm2bids.json*)
- [ ] I've described the enhancement for an existing feature
- [ ] (optional) I've added some ideas about how to implement my suggestion
- [ ] I've given this issue the correct labels

### Description of Problem / Inefficiency:

TODO

### Additional Context / Screenshots:
Update README to add BET in the feature list 

Related to #66

**Comment by 4rnaudB** [comment]
Completed with #542
