### ISSUE TITLE
st_check_dependencies not telling the dependencies missing

### ISSUE THREAD

**Issue by KevinBerard** [shimming-toolbox/shimming-toolbox#268]
### Checklist

- [x] I've given this issue a self-descriptive, meaningful title (e.g. *Installation failure: problem creating launchers*)
- [x] I've described my environment
- [x] I've described the bug
- [x] I've described the steps to reproduce the behaviour
- [x] I've included screenshots
- [ ] I've given this issue the correct labels

### Environment details

- [x] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

Project version: 7c52ded8ec39678ea56cf6c556d55a52ff65ff6a

Operating System and version: Ubuntu21

Python version: 3.7 

Path to Python binary: /path/to/bin/python 

### Bug Description

I used st_check_dependencies and it didn't work properly according to @po09i . If I understood correctly it is that the st_check_dependencies is suppose to mention which dependencies that are missing more clearly.

### Reproduction Steps

Freshly installed Ubuntu21 with installation of dcm2niix and FSL according to the [guide](https://shimming-toolbox.org/en/latest/getting_started/installation_st/linux.html) . I installed shimming-toolbox then use st_check_dependencies to verify dependencies.

### Potential Reasons behind Bug:

I had a problem in my PATH where fsl and dcm2niix were not included. This means the call to find prelude was wrong.
### Screenshots:

![Screenshot from 2021-05-20 18-32-14](https://user-images.githubusercontent.com/83981856/119059776-fa492100-b99e-11eb-8d6b-84b697d99ae2.png)

**Comment by KevinBerard** [comment]
Issue is still not fixed with the latest version on master

![image](https://user-images.githubusercontent.com/83981856/127384532-8d4cc6a7-b9c2-4793-a935-569f66dca299.png)

**Comment by gaspardcereza** [comment]
On the second screenshot, you are using windows. It is normal that `st_check_dependencies` does not work here  as we use the `which` command to check if the dependencies are installed and this command is not available in the Windows command prompt (that uses `where`).
