### ISSUE TITLE
demo_realtime_zshimming example missing a file

### ISSUE THREAD

**Issue by KevinBerard** [shimming-toolbox/shimming-toolbox#271]
### Checklist

- [X] I've given this issue a self-descriptive, meaningful title (e.g. *Installation failure: problem creating launchers*)
- [X] I've described my environment
- [X] I've described the bug
- [X] I've described the steps to reproduce the behaviour
- [X] I've included screenshots
- [X] I've given this issue the correct labels

### Environment details

- [X] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/getting_started/installation_gui.html)

Project version: 7c52ded8ec39678ea56cf6c556d55a52ff65ff6a

Operating System and version: Ubuntu21

Python version: 3.7 

Path to Python binary: /home/kb/anaconda3/envs/shim_venv/bin/python 

### Bug Description

During the testing of shimming-toolbox with the [demo_realtime_zshimming](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/examples/demo_realtime_zshimming.sh), the step where you create a fieldmap point out that there is a missing file (sub-example_magnitude1.nii.gz). After investigation, the file is missing after the download along with the sub-example_magnitude2.nii.gz

### Reproduction Steps

Follow the [steps](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/examples/demo_realtime_zshimming.sh) until the line "st_prepare_fieldmap "sub-example_phasediff.nii.gz" -mag "sub-example_magnitude1.nii.gz" -unwrapper "prelude" -output "sub-example_fieldmap.nii.gz""

### Potential Reasons behind Bug:

Maybe there are files missing in the download of testing_data.

### Screenshots:

![Screenshot from 2021-05-27 15-33-29](https://user-images.githubusercontent.com/83981856/119886542-16017980-bf01-11eb-96c9-6271c0fc73e5.png)
![Screenshot from 2021-05-27 15-33-58](https://user-images.githubusercontent.com/83981856/119886545-16017980-bf01-11eb-80cc-6c559c3facce.png)
![Screenshot from 2021-05-27 15-34-03](https://user-images.githubusercontent.com/83981856/119886547-169a1000-bf01-11eb-9608-fe4baaa57216.png)

**Comment by po09i** [comment]
@KevinBerard I tried it on my hand and it seems to work fine. I can see in your screenshot this line where magnitude1 seems to be parsed:
`INFO:dcm2bids.sidecar:_magnitude1  <-  015_._gre_field_mapping_PMUlog_2_20200817104950_e1`

I think the error comes from running `st_dicom_to_nifti` in the `shimming-toolbox/` directory rather than in the `shimming-toolbox/testing_data/realtime_zshimming_data` directory. Maybe you forgot to cd in the folder after downloading `testing_data` like the script suggests?

**Comment by KevinBerard** [comment]
That's exactly what happened
