### ISSUE TITLE
Problem with reordering the B1 maps after nifti conversion

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#281]
### Environment details

Project version: Master branch (2021/06/10)

Operating System and version: Catalina (Mac OS)

Python version: 3.7

### Bug Description
I tried to scaled B1 maps from our last acquisition at the MNI (acdc_spine_7t_007) and realized they are not reshuffled correctly by `load_nifti` (slices are still shuffled).  

### Reproduction Steps
Need access to dicoms from our last acquisition (acdc_7t_007). After converting dicoms into nifti, run `shimming-toolbox.load_nifti` on a  `b1map_standard` nifti. 

### Potential Reasons behind Bug:
Probably because some B1 mapping acquisitions are interleaved and others are not not --> Currently checking this

**Comment by gaspardcereza** [comment]
In order to better organise my investigations, here's a sum up of the different B1 mapping sequences we ran on the MNI's Terra so far: 

- **acdc_spine_7t_001p (2020/02/21)**
  - rfmap_ax
     - 48 uncombined dicoms
     - not inverted
  - rfmap_ax_scale10
     - 144 uncombined dicoms
     - not inverted
  - rfmap_sag
    - 144 uncombined dicoms
    - **inverted**
  - standard (6)
     - 400 uncombined dicoms
     - not inverted
  - standard (106)
    - 560 uncombined dicoms
    - not inverted
 
- **acdc_spine_7t_002p (2020/09/23)**
  - rfmap_ax
    - 560 uncombined dicoms
    - not inverted
  - tfl_rfmap_B1shim (59)
    - 16 combined dicoms   
  - tfl_rfmap_B1shim (60)
    - 16 combined dicoms
  - tfl_rfmap_B1shim_scal5
    - 16 combined dicoms   
  - tfl_rfmap_B1shim_5mm
    - 16 combined dicoms
  - tfl_rfmap_B1shim_5mm_BW150
    - 16 combined dicoms
  - tfl_rfmap_B1shim_5mm_flip10
    - 16 combined dicoms
  - tfl_rfmap_B1shim_5mm_flip15_5mm
    - 16 combined dicoms
  - tfl_rfmap_B1shim_5mm_flip20_5mm (66)
    - 16 combined dicoms
  - tfl_rfmap_B1shim_5mm_flip20_5mm (67)
    - 256 uncombined dicoms
    - not inverted

- **coil_test_np11_04_02 (2021/03/19)**
  - standard
    - 400 uncombined dicoms
    - not inverted

- **acdc_spine_7t_003p (2021/03/26)**
  - b1_map_standard_300V
    - 800 uncombined dicoms
    - not inverted
    - save uncombined: `off`
  - b1_map_standard_400V
    - 800uncombined dicoms
    - not inverted
    - save uncombined: `off`
  - b1_map_standard_500V
    - 800 uncombined dicoms
    - not inverted
    - save uncombined: `off`
  - b1_map_standard_650V
    - 48 uncombined dicoms
    - not inverted
    - save uncombined: `off`

- **acdc_spine_7t_005 (2021/04/08)**
  - b1map_standard_REF
    - 448 uncombined dicoms
    - **inverted**

- **acdc_spine_7t_007 (2021/06/16)**
  - b1map_standard_2x2x3
    - 448 uncombined dicoms
    - **inverted**
  - b1map_standard_4x4x4
    - 448 uncombined dicoms
    - **inverted**
  - b1map_standard_2x2x3_RFshimmed
    - 448 uncombined dicoms 
    - **inverted**

- **acdc_spine_7t_008p (2021/05/21)**
  - b1map_standard_3mm
    - 64 uncombined dicoms
    - **inverted**
  - b1map_standard_3mm_15slc
    - 64 uncombined dicoms
    - **inverted**
  - b1map_standard_3mm_1slc_REF500
    - 16 uncombined dicoms
    - **inverted**
  - b1map_standard_3mm_8slc_REF300
    - 128 uncombined dicoms
    - **inverted**

**Comment by gaspardcereza** [comment]
@jcohenadad @evaalonsoortiz I found something really weird: For many standard B1 mapping acquisitions, the `save uncombined` option was off (e.g. in ACDC_spine_7t_003p from 2021/03/26), but we still got uncombined maps only... 

In checked the fact that the option was unchecked in the pdf files (in the "system-miscellaneous" section). I really don't understand why we didn't get recombined maps...

**Comment by jcohenadad** [comment]
> @jcohenadad @evaalonsoortiz I found something really weird: For many standard B1 mapping acquisitions, the `save uncombined` option was off (e.g. in ACDC_spine_7t_003p from 2021/03/26), but we still got uncombined maps only...
> 
> In checked the fact that the option was unchecked in the pdf files (in the "system-miscellaneous" section). I really don't understand why we didn't get recombined maps...

can you please:
- add URL to the PDF
- mention the scan number (and the page) on the PDF that corresponds to the problematic dataset

that way i will be able to quickly check

**Comment by gaspardcereza** [comment]
@jcohenadad 
[Link to the PDF](https://drive.google.com/file/d/1Y2NLFE_LGaV8QLun3ob-d7NMcP2bTmWl/view?usp=sharing)
Any standard b1 mapping sequence is concerned (there are 4 of them). 
The setting "save uncombined" is in the section `system - Miscellaneous`

**Comment by jcohenadad** [comment]
Just to be clear: when you say "but we still got uncombined maps only...", are you referring to:
- Rx uncombined, or
- Tx uncombined (and Rx combined)?

If you are referring to the latter, then this is what is expected (the flag "save uncombined" refers to the Rx elements).

**Comment by gaspardcereza** [comment]
> Just to be clear: when you say "but we still got uncombined maps only...", are you referring to:
> 
> * Rx uncombined, or
> * Tx uncombined (and Rx combined)?
> 
> If you are referring to the latter, then this is what is expected (the flag "save uncombined" refers to the Rx elements).

Ok in that case it is normal then as I was referring to Tx maps.

**Comment by gaspardcereza** [comment]
I went through all b1 mapping acquisitions we did and isolated two different cases: 
- dcm2niix inverts the coil ordering when storing the b1 maps in the niftis
- dcm2niix keeps the coil ordering

I'll now try to find what could be the reason between this unexpected behavior by going through the dicom tags and the pdf from the different acquisitions.
