### ISSUE TITLE
Make a release 🚀 

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#285]
### Checklist

- [ ] I've given this issue a self-descriptive, meaningful title (e.g. *Implement optimization algorithms for shimming*)
- [ ] I've described the new feature and its expected behaviour
- [ ] I've described the usage scenario for the new feature
- [ ] (optional) I've added some ideas about how to implement my suggestion
- [ ] I've given this issue the correct labels

### Feature Description:

Now that ST has been presented at ISMRM, people will start clicking the download button so we should probably have an official release sooner rather than later-- also, in the context of https://github.com/shimming-toolbox/shimming-toolbox/pull/284, having a release will prevent the ugly:
![image](https://user-images.githubusercontent.com/2482071/125090178-11ea7f00-e09d-11eb-81ac-091685d6380a.png)

I suggest we go for a v0.1

**Comment by po09i** [comment]
We currently have v0.1-beta, not sure why that is not displayed. Maybe the badge does not display pre-releases. In any case we could move to an actual release.

**Comment by jcohenadad** [comment]
> Maybe the badge does not display pre-releases.

yup

**Comment by po09i** [comment]
We should make a release before merging #284 to avoid the ugly "no-release" badge. However, we could wait for the sequencer PR so that the api is included in the release. Otherwise we can create a release now and another one later once the sequencer is fully implemented (API and CLI).

**Comment by po09i** [comment]
![Screen Shot 2021-07-29 at 15 37 45](https://user-images.githubusercontent.com/47249340/127555223-adf50c0f-ba53-408e-80bd-e0a2d5ea3994.png)
We just released Shimming Toolbox v0.1! 👌🏽 We can close this issue
