### ISSUE TITLE
q/sform information lost between fieldmap and subsequent processing

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#291]
### Checklist

- [x] I've given this issue a self-descriptive, meaningful title (e.g. *Installation failure: problem creating launchers*)
- [ ] I've described my environment
- [x] I've described the bug
- [x] I've described the steps to reproduce the behaviour
- [ ] I've included screenshots
- [x] I've given this issue the correct labels

### Environment details

- [x] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

Project version:

Operating System and version:

Python version: 3.x.x 

Path to Python binary: /path/to/bin/python 

### Bug Description

While debugging #289 I noticed that images processed by shimming toolbox and derived from fieldmaps (and possibly other input images) lost important q/sform fields. Example:

<details><summary>testing_data/realtime_zshimming_data/nifti/sub-example/fmap/sub-example_fieldmap.nii.gz</summary>

```console
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	0.000000 0.000000 3.000000 -3.614460 
qto_xyz:2	-2.916670 0.000000 -0.000000 101.766998 
qto_xyz:3	0.000000 2.916670 -0.000000 -129.854645 
qto_xyz:4	0.000000 0.000000 0.000000 1.000000 
qform_xorient	Anterior-to-Posterior
qform_yorient	Inferior-to-Superior
qform_zorient	Left-to-Right
sform_name	Scanner Anat
sform_code	1
sto_xyz:1	0.000000 0.000000 3.000000 -3.614460 
sto_xyz:2	-2.916670 0.000000 0.000000 101.766998 
sto_xyz:3	0.000000 2.916670 0.000000 -129.854645 
sto_xyz:4	0.000000 0.000000 0.000000 1.000000 
sform_xorient	Anterior-to-Posterior
sform_yorient	Inferior-to-Superior
sform_zorient	Left-to-Right
```

</details>

<details><summary>fig_gx_gradient.nii.gz produced by test/shim/test_realtime_shim:test_output_figure()</summary>

```console
qform_name	Unknown
qform_code	0
qto_xyz:1	0.000000 0.000000 3.000000 -3.614460 
qto_xyz:2	-2.916670 0.000000 -0.000000 101.766998 
qto_xyz:3	0.000000 2.916670 -0.000000 -129.854645 
qto_xyz:4	0.000000 0.000000 0.000000 1.000000 
qform_xorient	Anterior-to-Posterior
qform_yorient	Inferior-to-Superior
qform_zorient	Left-to-Right
sform_name	Unknown
sform_code	2
sto_xyz:1	0.000000 0.000000 3.000000 -3.614460 
sto_xyz:2	-2.916670 0.000000 0.000000 101.766998 
sto_xyz:3	0.000000 2.916670 0.000000 -129.854645 
sto_xyz:4	0.000000 0.000000 0.000000 1.000000 
sform_xorient	Anterior-to-Posterior
sform_yorient	Inferior-to-Superior
sform_zorient	Left-to-Right
```

</details>

This could be problematic, notably when dealing with resampling from one space to the other (see eg https://github.com/shimming-toolbox/shimming-toolbox/pull/289#issuecomment-877439001). 

Suggestion: make sure the NIFTI headers are minimally altered by the processing pipeline.

We could add tests to it!!

**Comment by jcohenadad** [comment]
A collateral issue is that some software cannot interpret images with qform_code = 0. Example for ITKsnap:

![image](https://user-images.githubusercontent.com/2482071/126553816-3406195c-9d18-4022-a686-a438673be080.png)

**Comment by po09i** [comment]
This was fixed in realtime_shim and test_realtime_shim in https://github.com/shimming-toolbox/shimming-toolbox/pull/289/commits/18def2842c521d8e13829496a0fa6836bf92b2de from PR #289 by adding a correct header when creating a nibabel object.
