### ISSUE TITLE
Set up unit test suite

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#3]
- Setup pytest
- Add in Travis CI

**Comment by mathieuboudreau** [comment]
I have those done [mb/setup](https://github.com/shimming-toolbox/shimming-toolbox-py/tree/mb/setup). I don't have sufficient permissions to "turn on" the CI from the Travis side though:

<img width="1067" alt="Capture d’écran 2020-07-03 à 22 13 56" src="https://user-images.githubusercontent.com/1421029/86502520-88fa8280-bd7a-11ea-8713-8011154a5fa4.png">

**Comment by jcohenadad** [comment]
@mathieuboudreau i'm trying to get you the permissions-- are you on https://travis-ci.org/ or https://travis-ci.com/?

**Comment by jcohenadad** [comment]
ah, i guess we should use travis-ci.com: https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com#:~:text=2%20Answers&text=Travis%20CI%20originally%20created%20two,com%20(see%20official%20announcement)%3A

**Comment by mathieuboudreau** [comment]
Ahh yes - I've encountered this issue before - frustrating!

**Comment by jcohenadad** [comment]
i didn't see a place to allow you to modify the settings, but i _think_ it should be active now, waiting for new builds...

![Screen Shot 2020-07-03 at 9 28 33 PM](https://user-images.githubusercontent.com/2482071/86502721-3cac4400-bd74-11ea-83ef-5d36e33c545b.png)

**Comment by mathieuboudreau** [comment]
Yup - I just ran it by pushing an empty change in the PR I opened earlier.
