### ISSUE TITLE
Improving the low testing coverage of certain functions 

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#307]
### Description of Problem / Inefficiency:
I had a look at the [testing coverage results](https://coveralls.io/github/shimming-toolbox/shimming-toolbox?branch=master) on the master branch and noticed that some parts of the `shimming-toolbox ` (e.g. the `utils` functions) have very low coverage. 

![image](https://user-images.githubusercontent.com/54723104/134738996-af0bd50f-7e7b-4b86-b035-4493b7a9778a.png)

### Implementation Suggestion:
Implementing a few additional unit tests would allow us to easily improve our coverage by a few %.

**Comment by po09i** [comment]
We are doing pretty good! There are still improvements that can be done, but I think we can close the issue
