### ISSUE TITLE
Speed up local tests with pytest-xdist

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#324]
### Description of Problem / Inefficiency:
The testing suite is starting to take some non-negligable amount of time

### Implementation Suggestion:
There is a multi-core expansion to pytest  `pytest-xdist`. We could use that to speed local development

pip install pytest-xdist

**Comment by jcohenadad** [comment]
FWIW use used xdist in SCT and then decided to not use it anymore for a few reasons described in this PR: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3212
