### ISSUE TITLE
getting_started in documentation uses a README file

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#325]
In the [getting started](https://shimming-toolbox.org/en/latest/getting_started/getting_started.html) section of the documentation, the page is generated by including a README.rst file into the content. This is not elegant and we think there would be better ways to generate this page.

**Comment by jcohenadad** [comment]
my suggestion was simply to rename the file README --> getting_started

**Comment by po09i** [comment]
We changed the website and we no longer have a getting_started page
