### ISSUE TITLE
Recycle read_nii() function from old PR

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#33]
This PR https://github.com/shimming-toolbox/shimming-toolbox-py/pull/18 introduced a function read_nii(), which was then removed because out-of-scope.

The code developed could still be useful, notably for https://github.com/shimming-toolbox/shimming-toolbox-py/issues/13, hence it is uploaded here:

[read_nii.py.zip](https://github.com/shimming-toolbox/shimming-toolbox-py/files/4984186/read_nii.py.zip)

**Comment by po09i** [comment]
read_nii currently being used
