### ISSUE TITLE
st_dicom_to_nifti hangs when connected to SYNGO via Ethernet

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#334]
### Environment details
Project version: a6fa292
Mac on macOS Monterey (12.0.1)

### Bug Description
When scanning at the UNF, we connect to the scanner via ethernet so that a drive can be mounted on SYNGO. We then run the `realtime_shimming.sh` script. The script hangs when executing `st_dicom_to_nifti`. This is the last line being logged before the hang: 

```
INFO:dcm2bids.dcm2bids:moving acquisitions into BIDS folder
```

### Reproduction Steps
Connect at the UNF to SYNGO, run `st_dicom_to_nifti`

### Potential Reasons behind Bug:
Since we don't have internet, but it looks like we are (we are connected via ethernet), I think dcm2bids is hanging trying to retrieve its version in this [line](https://github.com/UNFmontreal/Dcm2Bids/blob/master/dcm2bids/dcm2bids.py#L143).

**Comment by po09i** [comment]
We are using dcm2bids v2.1.4 instead of the latest 2.1.6, I will test if that solves the problem.

**Comment by po09i** [comment]
Using 2.1.6 did not solve the problem. It still hangs at the scanner

**Comment by po09i** [comment]
Opened an issue on [dcm2bids](https://github.com/UNFmontreal/Dcm2Bids/issues/149)

**Comment by kousu** [comment]
Here's a small script to help reproduce:

```
#!/usr/bin/env python3

import socket

socket.setdefaulttimeout(3)
socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("8.8.8.8", 53)) # DNS
#socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("132.207.6.35", 443)) # try HTTPS in case DNS has some weird config
```

**Comment by po09i** [comment]
This was fixed on dcm2bids side: https://github.com/UNFmontreal/Dcm2Bids/issues/149
