### ISSUE TITLE
dcm2bids not recognized when using st_dicom_to_nifti outside the venv

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox#343]
### Bug Description
dcm2bids is not recognized when using `st_dicom_to_nifti` outside the virtual environment. This is an unexpected behaviour since we want the user to use all the CLIs that don't require external dependencies. dcm2bids is not an external dependency.

### Reproduction Steps
Launch `st_dicom_to_nifti` outside the venv

### Potential Reasons behind Bug:
We updated dcm2bids and dcm2niix to be an internal dependency. It is therefore downloaded in the venv. We previously used subprocess to call the users dcm2bids and dcm2niix but it does not exists outside the venv.

### Screenshots:
![Screen Shot 2022-02-17 at 12 50 17 PM](https://user-images.githubusercontent.com/47249340/154540882-3326d119-7943-41cc-97db-4a154cc627bc.png)

**Comment by gaspardcereza** [comment]
I managed to launch the subprocess by inputting the full path of the venv where the targetted binary is located as follows:

`subprocess.run(['/Users/gaspard/shimming-toolbox/python/envs/st_venv/bin/dcm2bids_scaffold', '-o', path_nifti], check=True)`

However this resulted in another error later on:
![image](https://user-images.githubusercontent.com/54723104/154569163-8e719cad-3513-4362-9bce-38c2766a4a37.png)

**Comment by po09i** [comment]
Possible solution: copy the binaries in the shimming-toolbox bin PATH. This takes care of everything at the installation, the code stays the same. This has an added effect of adding dcm2* to the PATH of the user.

**Comment by po09i** [comment]
This seems to be the same problem as the on discovered on the plugin. More info here https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/issues/21
