### ISSUE TITLE
Add example scenario for realtime z-shimming

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#37]
A few specifications:
- The scenario would be based on the previous [Matlab implementation ](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/example/realtime_zshim.m)
- Would be using our [testing data](https://github.com/shimming-toolbox/data-testing/tree/master/realtime_zshimming_data)
- The example scripts should be shell scripts, wrapping the various CLIs, with a short explanation of what each CLI does. That way, users will be able to copy/paste and go through the example script line by line, and play with the various inputs/outputs and change parameters for each CLIs. This follows the philosophy of other example scripts, e.g. [SCT's](https://github.com/neuropoly/spinalcordtoolbox/blob/master/batch_processing.sh).

**Comment by jcohenadad** [comment]
Relevant comment: https://github.com/shimming-toolbox/shimming-toolbox-py/issues/13#issuecomment-666004847

**Comment by po09i** [comment]
Issue can be closed, PR #92 implements a shell script which demos how to use the toolbox and realtime zshimming
