### ISSUE TITLE
Startup failure of the Shimming Toolbox in FSL after a clean install on two Linux distributions (CentOS-7 and Ubuntu22.04)

### ISSUE THREAD

**Issue by chaigner** [shimming-toolbox/shimming-toolbox#433]
### Environment details

- [x] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

Project version: shimmingtoolbox==0.1.0

Operating System and version: I have tried two different Linux distributions: CentOS-7 and Ubuntu22.04

Python version: 3.9.15 

Path to Python binary: ~/shimming-toolbox/python/bin/python

### Bug Description
After a clean install, I start FSL with `shimming-toolbox`, which opens the FSL GUI.
The FSL GUI runs well, and I can load DICOMs, change the view and open different windows etc. 
However, after clicking on Settings->Ortho View 1->Shimming Toolbox, a small black rectangular object appears on the top left corner of FSL (see screenshot below) instead of the Shimming Toolbox plugin described in the installation guidelines.
In addition, I get an reproducible command line error:
 ```
 File "/home/aigner01/fsleyes-plugin-shimming-toolbox/fsleyes_plugin_shimming_toolbox/st_plugin.py", line 387, in on_choice
    selection = self.choice_box.GetString(self.choice_box.GetSelection())
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at /home/conda/feedstock_root/build_artifacts/wxpython_1671479590537/work/ext/wxWidgets/src/gtk/choice.cpp(296) in GetString(): invalid index
```
For the full output see:  https://pastebin.com/b3YwRQE5 

### Reproduction Steps
I have tried it on two computers with different Linux distributions (CentOS-7 and Ubuntu22.04) and got the same error message.

### Potential Reasons behind Bug:
I think it might be connected to the "wxpython" package (I have version 4.2.0), but I could not fix the issue.

### Screenshots:
![image](https://user-images.githubusercontent.com/1242412/217219775-3b4bab51-fe09-46e0-aba5-82ffa5e02785.png)

**Comment by po09i** [comment]
Hi @chaigner, thanks for the complete bug report, I will take a look at your issue and report back as soon as I have a way to proceed.

Alex

**Comment by po09i** [comment]
@chaigner, I have looked into your issue and was able to reproduce it. I have implemented a fix in this [branch](https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/pull/54). You can test it by following the instructions on our [website](https://shimming-toolbox.org/en/latest/user_section/installation.html#id2) and adding the line `git checkout ad/linux-launch-bug` to select a specific version. Here are the manipulations for convenience:

```
git clone https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox.git
cd fsleyes-plugin-shimming-toolbox
git checkout ad/linux-launch-bug
make install
source ~/.bashrc
shimming-toolbox
```

Let me know if that resolves your issue. I will merge the branch afterwards.

Alex

**Comment by chaigner** [comment]
Dear Alex,

thx for your quick response and fix of the startup bug. 
I just tried it again, and it seems to work perfectly now. 
Thank you so much for your hard work and for ensuring everything is running smoothly.

Best regards,
Christoph

**Comment by po09i** [comment]
No problem! The fix is now on master.
