### ISSUE TITLE
Bug for the quadprog optimizer

### ISSUE THREAD

**Issue by Aurelienpujolm** [shimming-toolbox/shimming-toolbox#478]
### Checklist

- [x] I've given this issue a self-descriptive, meaningful title (e.g. *Installation failure: problem creating launchers*)
- [x] I've described the bug
- [x] I've given this issue the correct labels

In scenarios involving multiple coils for shimming, a potential bug can arise if some coils have a coef_sum_max set to np.inf, while others do not. One possible dirty  approach to address this issue, could be to remove the if statement within the for loop where we check whether coil.coef_sum_max differs from np.inf. Following this, you could keep the subsequent lines within the loop. Additionally, it might be advisable to omit the case involving np.all(sum_constraints == 0) and maintain the version containing the else clause for both real-time and dynamic shimming.

Another way to tackle this could involve removing the lines from sum_constraints where coef.sum_max = np.inf, to not have a line of sum_constraints with zeros. However, careful consideration is required to ensure that sum_constraints does not end up being empty (particularly if all the coils have no restrictions on the sum of currents).

**Comment by po09i** [comment]
> In scenarios involving multiple coils for shimming...

Can you link to where in the code you are talking about? It could be helpful to show a code snippet.

> However, careful consideration is required to ensure that sum_constraints does not end up being empty (particularly if all the coils have no restrictions on the sum of currents).

Is this a problem because the matrix has to be defined? What if all coils have no restrictions, how do we define the matrix?

**Comment by Aurelienpujolm** [comment]
> > In scenarios involving multiple coils for shimming...
> 
> Can you link to where in the code you are talking about? It could be helpful to show a code snippet.
> 
```
for i_coil in range(n_coils):
    coil = self.coils[i_coil]
    end_index = start_index + coil.dim[3]
    if coil.coef_sum_max != np.inf:
        pressure = np.max(np.abs(self.pressure_max), np.abs(self.pressure_min))
        sum_constraints[i_coil, 0] = coil.coef_sum_max / (coil.dim[3] * pressure)
        g_bis[i_coil, start_index: end_index] = 1
    start_index = end_index
```
Here for the dirty way, you can just remove the if statement, and keep the rest (pressure = .... ) 
> > However, careful consideration is required to ensure that sum_constraints does not end up being empty (particularly if all the coils have no restrictions on the sum of currents).
> 
> Is this a problem because the matrix has to be defined? What if all coils have no restrictions, how do we define the matrix?

And for your second point, in the case, if all coils have no restrictions, it will look like what is done before : (this is in the pmu optimizer
```
if np.all(sum_constraints == 0):

    g = np.block([[-np.eye(n), -np.eye(n)], [np.eye(n), -np.eye(n)],
                  [- delta_pressure * - np.eye(n), np.zeros([n, n])],
                  [delta_pressure * - np.eye(n), np.zeros([n, n])],
                  [delta_pressure * np.eye(n), np.zeros([n, n])],
                  [- delta_pressure * np.eye(n), np.zeros([n, n])]])
    # dim(g) = (6n, 2n)

    h = np.block([[np.zeros([n, 1])], [np.zeros([n, 1])],
                  [-lb], [-lb], [ub], [ub]])

    # dim(h) = (6n, 1)
```
So here before, sum_constraints has to be defined, but you can maybe find a way to not have it defined.

**Comment by Aurelienpujolm** [comment]
Just as a side note, this has to be done if both dynamic and pmu optimizer.
