### ISSUE TITLE
old format dcm2bids.json when using fsleyes-plugin-shimming-toolbox install script

### ISSUE THREAD

**Issue by eozh** [shimming-toolbox/shimming-toolbox#489]
I have installed the shimming toolbox according to the website instructions, starting with
`git clone https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox.git`

After the installation completed, dcm2bids version 3.0.1 got installed. The dcm2bids.json file in the fresh install directory had  2.x format, which was incompatible with dcm2bids 3.x and resulted in errors while running "Dicom To Nifti" tool. As a workaround I downloaded the latest version of dcm2bids.json from this repository and it fixed those errors.

The problem seems to be caused by fsleyes-plugin-shimming-toolbox `install_shimming_toolbox.sh` script downloading a specific snapshot of shimming-toolbox repository that includes the old-style dcm2bids file, but then installing the current version of dcm2bids package.

**Comment by po09i** [comment]
Thanks for the report, I will update the snapshot to a more recent version and it should fix the problem

**Comment by po09i** [comment]
The plugin has been updated and it should now use the updated config file. You can update to the new version by following the same installation instructions.
