### ISSUE TITLE
Add functions to read Flip Angle maps (for RF shimming purpose)

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/shimming-toolbox#50]
## Context
We want our shimming-toolbox to include some RF shimming features. 
The first step of the RF shimming process is to read the flip angle maps measured by the scanner. In subsequent issues, these maps will be used to optimize the shimming coefficients for RF homogenization, which might significantly improve the image quality, especially at ultra high field. 

## Goal
Here we will only focus on how to read these maps. They will first have to be converted to `NIFTI` files (following the BIDS convention) and then reconstructed as python complex arrays (ready to be used by an optimization algorithm).

## Testing data
I will base my code on RFmaps that we acquired on the MNI's 7T scanner (Siemens Terra). The corresponding `DICOM` files (which have an `.IMA` extension) will be added to [our data-testing repository](https://github.com/shimming-toolbox/data-testing).

**Comment by po09i** [comment]
We can now perform RF shimming
