### ISSUE TITLE
Remove unneeded example modules

### ISSUE THREAD

**Issue by jidicula** [shimming-toolbox/shimming-toolbox#70]
The docstring in this file claims that `INPUT` is a folder of dicom files, but the `click.argument` implies that the input is in fact a binary file being read into memory, *not* a directory. However, I don't know enough about the functionality of this module to be able to correct it. Could this be reviewed by the file's author?

**Comment by po09i** [comment]
referencemaps and b0map CLIs and APIs were examples at the beginning of the project. Now that more functions are implemented, I think they can be removed.
