### ISSUE TITLE
Consider changing coil to be a Class instead of an np.array

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#79]
As of a1bb94318a9559d04857f1c7541e1c340bc22ff1, coil object generated by `shimmingtoolbox.coils.XXX` is a np.array: `[nx, ny, nz, coeffs]`. The problem with this format, is that we are missing relevant information, such as:
- units 
- labels (eg: 'Z', 'XY', etc.)

a suggestion would be to make `coil` a Class which would include the properties above

**Comment by po09i** [comment]
After design discussion with the team, we think it makes sense to have coil profiles as a class, some pros: 
- Allows to shift the constraints from the optimizers to the coil profile class (more modular) 
- Allows to easily handle if we want more than one coil profile for the optimizer. This was a problem for the constraints

Some constraints to think about:
- Total current
- Current per channel
- Realtime current constraint

**Comment by po09i** [comment]
Coil is now a class
