### ISSUE TITLE
Setup conventions for CLI and document them

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#87]
We need to decide on a couple of things:

### Prefix for CLIs

As of today, we use "st_", which has pros/cons;
- pros: short
- cons: does not "resonate" in people's mind 

Suggestions (pls contribute):
- shim_
  - con: shim could be a keyword used in the suffix
- shim_tool_
  - con: Too long
- shimt_
- shimpy_
- shrimp_ (extra plus: we can have a mascot for the project 🦐 )
- sht_

### Suffix

The convention should be:
- xxx_action_object

Examples:
- xxx_compute_bla
- xxx_unwrap_phase
- xxx_run_shimming

### Dash

I personally like the single dash option with more than one char. 
- pros: less confusing (one choice)
- cons: not POSIX compatible-- but not necessarily a problem for our user base

### Documentation

Once we decide on conventions, we should document them on the [wiki](https://github.com/shimming-toolbox/shimming-toolbox-py/wiki)

**Comment by po09i** [comment]
I added a couple of suggestions, I still like `shim_` better though.

**Comment by lcbMGH** [comment]
I like `st_` for concision and avoiding repeating the word shim if it comes up in commands

**Comment by jidicula** [comment]
I like `shrimp_` because it allows us to have a mascot, has an emoji (🦐 ), and sounds cute. In lieu of this, I vote `shim_`.
