### ISSUE TITLE
Create CLI for creating mask

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox#88]
## Context

Command Line Interface allow to use the python software on the command line. Currently, the masking methods implemented are [threshold](https://github.com/shimming-toolbox/shimming-toolbox-py/blob/master/shimmingtoolbox/masking/threshold.py) and [shape](https://github.com/shimming-toolbox/shimming-toolbox-py/blob/master/shimmingtoolbox/masking/shapes.py) where shape can be a square or a cube. The goal is to implement a basic CLI that enables to call the different implemented masking methods while considering what will be implemented in the future (SCT, BET)

## Discussion
Suggestion for name:
- st_mask

Suggestions for flags:

~~~
-i <file> input
-method {sct, bet, shape, threshold}
-shape {cube, ball} Only for method=shape
-size <int> Radius of the shape in voxel (not mm). Only for method=shape
~~~

Potential new feature: have it in mm. To discuss...

## To get started
Where: [shimmingtoolbox/cli](https://github.com/shimming-toolbox/shimming-toolbox-py/tree/master/shimmingtoolbox/cli)
Example: [shimmingtoolbox/cli/download_data](https://github.com/shimming-toolbox/shimming-toolbox-py/blob/master/shimmingtoolbox/cli/download_data.py)
Useful link to start [contributing](https://shimming-toolbox.org/en/latest/3_contributing/CONTRIBUTING.html)

**Comment by jidicula** [comment]
> To get started

I like this section – I'll try to adopt in my projects and at my work too! Definitely helpful for newcomers looking for an example to adapt for the ticket's desired feature 😁
